from dotenv import load_dotenv
import os


load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")
PROXY = os.getenv("PROXY")
BOSS_ID = os.getenv("BOSS_ID")
MOVE_THRESHOLD = 2.5
INTERVAL = "15m"
COUNT_CANDLES = 8
ORDERBOOK_VOLUME_THRESHOLD = 12
COEFFICIENT_VOLUME_THRESHOLD = 5
DIST_TO_DENSITY = 2.0
TIME_TO_NEXT_ORDERBOOK_ALERT = 900
